# Generated by Django 4.2.5 on 2023-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('type_of_service', models.IntegerField()),
                ('device_name', models.CharField(max_length=100)),
                ('requestDate', models.DateTimeField()),
                ('is_done', models.BooleanField()),
            ],
            options={
                'db_table': 'customer_service',
            },
        ),
    ]
